apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: test-dp
    cicd_env: canary
  name: test-dp
  namespace: shencq
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-dp
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: test-dp
    spec:
      containers:
      - command:
        - /bin/aaa
        image: something:not-found
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 56Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31
